version: '3.8'

services:
  backend:
    image: certelen/azu_cafe_django:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

    env_file:
      - ../.env
  frontend:
    image: certelen/azu_cafe_aiogram:v1
    env_file:
      - ../.env
  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
